# Generated by Django 2.1.15 on 2020-04-24 16:08

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200423_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.restaurant_image_file_path),
        ),
    ]
