# Generated by Django 2.1.15 on 2020-04-28 11:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='avatar.png', upload_to=core.models.profile_image_file_path),
        ),
    ]
